steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/keen-ascent-102617/domandpom-app', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/keen-ascent-102617/domandpom-app']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'domandpom-app', '--image', 'gcr.io/keen-ascent-102617/domandpom-app', '--region', 'northamerica-northeast1', '--platform', 'managed']
  images:
  - gcr.io/keen-ascent-102617/domandpom-app
  